<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Cashbook — {{ $account->account_name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a1a1a; }
        .header { text-align: center; border-bottom: 3px double #1a1a1a; padding-bottom: 10px; margin-bottom: 16px; }
        .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
        .header h2 { margin: 4px 0 0; font-size: 14px; }
        table.meta { width: 100%; margin-bottom: 12px; }
        table.meta td { font-size: 11px; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th, table.data td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        table.data th { background: #f2f2f2; }
        table.data td.num, table.data th.num { text-align: right; }
        .totals { margin-top: 14px; width: 100%; }
        .totals td { padding: 3px 0; font-weight: bold; }
        .footer { margin-top: 24px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Borno State Geographic Information Service</h1>
        <h2>Cashbook</h2>
    </div>

    <table class="meta">
        <tr>
            <td><strong>Account:</strong> {{ $account->account_name }}</td>
            <td><strong>Bank:</strong> {{ $account->bank_name }}</td>
            <td><strong>Account Number:</strong> {{ $account->account_number }}</td>
            <td><strong>Type:</strong> {{ ucfirst($account->account_type) }}</td>
            <td><strong>Fiscal Year:</strong> FY {{ $fiscalYear?->name ?? 'All' }}</td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th>Date</th>
                <th>Reference</th>
                <th>Economic Code</th>
                <th>Description</th>
                <th class="num">Receipts</th>
                <th class="num">Payments</th>
                <th class="num">Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach($entries as $entry)
                <tr>
                    <td>{{ $entry->date->format('d/m/Y') }}</td>
                    <td>{{ $entry->reference ?? '—' }}</td>
                    <td>{{ $entry->economicCode?->code ?? '—' }}</td>
                    <td>{{ $entry->details }}</td>
                    <td class="num">{{ $entry->receipt_amount > 0 ? number_format((float) $entry->receipt_amount, 2) : '—' }}</td>
                    <td class="num">{{ $entry->payment_amount > 0 ? number_format((float) $entry->payment_amount, 2) : '—' }}</td>
                    <td class="num">{{ number_format((float) $entry->running_balance, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr><td>Opening Balance</td><td class="num">₦{{ number_format((float) $summary['opening_balance'], 2) }}</td></tr>
        <tr><td>Total Receipts</td><td class="num">₦{{ number_format((float) $summary['total_receipts'], 2) }}</td></tr>
        <tr><td>Total Payments</td><td class="num">₦{{ number_format((float) $summary['total_payments'], 2) }}</td></tr>
        <tr><td>Closing Balance</td><td class="num">₦{{ number_format((float) $summary['closing_balance'], 2) }}</td></tr>
    </table>

    <div class="footer">Generated by the BOGIS Finance Management System on {{ now()->format('d M Y H:i') }}.</div>
</body>
</html>
