<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Payment Voucher {{ $payment->treasury_receipt_voucher_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 13px; color: #1a1a1a; }
        .container { max-width: 720px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 3px double #1a1a1a; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 20px; text-transform: uppercase; }
        .header h2 { margin: 4px 0 0; font-size: 16px; }
        .header p { margin: 2px 0; font-size: 11px; }
        .badge { display: inline-block; padding: 3px 10px; background: #0d6efd; color: #fff; border-radius: 4px; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.info td { padding: 6px 4px; vertical-align: top; }
        table.info td:first-child { width: 38%; color: #555; }
        .amount-box { border: 2px solid #1a1a1a; padding: 12px; margin: 16px 0; text-align: center; }
        .amount-box .amount { font-size: 22px; font-weight: bold; }
        .amount-box .words { font-size: 11px; font-style: italic; margin-top: 6px; }
        .section-title { background: #f2f2f2; padding: 6px 10px; font-weight: bold; margin-top: 16px; }
        .signatures { margin-top: 50px; display: table; width: 100%; }
        .signatures div { display: table-cell; width: 33%; text-align: center; }
        .signatures .line { border-top: 1px solid #1a1a1a; margin: 0 20px; padding-top: 4px; font-size: 11px; }
        .footer { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Borno State Geographic Information Service</h1>
            <h2>Treasury Payment Voucher</h2>
            <p>BOGIS Finance Management System</p>
        </div>

        <div style="text-align: center; margin-bottom: 10px;">
            <span class="badge">{{ strtoupper($payment->status) }}</span>
        </div>

        <table class="info">
            <tr><td>Treasury Voucher No.</td><td><strong>{{ $payment->treasury_receipt_voucher_number }}</strong></td></tr>
            <tr><td>Date</td><td>{{ $payment->date_of_transaction->format('d M Y') }}</td></tr>
            <tr><td>Fiscal Year</td><td>FY {{ $payment->fiscalYear->name }}</td></tr>
            <tr><td>Account</td><td>{{ $payment->account->account_name }} — {{ $payment->account->bank_name }} ({{ $payment->account->account_number }})</td></tr>
            <tr><td>Account Type</td><td>{{ ucfirst($payment->account->account_type) }}</td></tr>
            <tr><td>Economic Code</td><td>{{ $payment->economicCode->code }} — {{ $payment->economicCode->name }}</td></tr>
            <tr><td>To Whom Paid</td><td>{{ $payment->from_whom_received_to_whom_paid ?? '—' }}</td></tr>
            <tr><td>Cheque/Mandate No.</td><td>{{ $payment->bank_credit_slip_cheque_mandate_number ?? '—' }}</td></tr>
            <tr><td>Department Voucher No.</td><td>{{ $payment->dept_voucher_number ?? '—' }}</td></tr>
            <tr><td>Payment Method</td><td>{{ strtoupper($payment->payment_method) }}</td></tr>
            <tr><td>Details</td><td>{{ $payment->details }}</td></tr>
        </table>

        <div class="amount-box">
            <div class="amount">₦{{ number_format((float) $payment->amount, 2) }}</div>
            <div class="words">{{ $amountInWords }}</div>
        </div>

        <div class="signatures">
            <div><div class="line">Prepared By<br>{{ $payment->creator?->name ?? '—' }}</div></div>
            <div><div class="line">Approved By<br>{{ $payment->approver?->name ?? '—' }}</div></div>
            <div><div class="line">Paid By<br>{{ $payment->payer?->name ?? '—' }}</div></div>
        </div>

        <div class="footer">Printed on {{ now()->format('d M Y H:i') }} — This voucher is generated by the BOGIS Finance Management System.</div>
    </div>
</body>
</html>
