<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1a1a1a; }
        .header { text-align: center; border-bottom: 3px double #1a1a1a; padding-bottom: 10px; margin-bottom: 14px; }
        .header h1 { margin: 0; font-size: 17px; text-transform: uppercase; }
        .header h2 { margin: 4px 0 0; font-size: 13px; }
        .header p { margin: 3px 0 0; font-size: 11px; }
        table.summary { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
        table.summary th, table.summary td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        table.summary th { background: #f2f2f2; font-size: 10px; }
        table.summary td.num { text-align: right; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th, table.data td { border: 1px solid #999; padding: 4px 5px; text-align: left; }
        table.data th { background: #f2f2f2; }
        table.data td.num, table.data th.num { text-align: right; }
        .footer { margin-top: 22px; font-size: 9px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Borno State Geographic Information Service</h1>
        <h2>{{ $title }}</h2>
        @if(isset($fiscalYear))
            <p>Fiscal Year: {{ $fiscalYear?->name ?? 'All' }} &mdash; Generated {{ now()->format('d M Y H:i') }}</p>
        @endif
    </div>

    @if(! empty($summary))
        <table class="summary">
            <tr>
                @foreach($summary as $stat)
                    <th>{{ $stat['label'] }}</th>
                @endforeach
            </tr>
            <tr>
                @foreach($summary as $stat)
                    <td class="num">{{ $stat['value'] }}</td>
                @endforeach
            </tr>
        </table>
    @endif

    <table class="data">
        <thead>
            <tr>
                @foreach($headings as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
                <tr>
                    @foreach($row as $cell)
                        <td @if(is_numeric($cell)) class="num" @endif>{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">Generated by the BOGIS Finance Management System.</div>
</body>
</html>
