<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bank Reconciliation Statement</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; }
        .header { text-align: center; border-bottom: 3px double #1a1a1a; padding-bottom: 10px; margin-bottom: 16px; }
        .header h1 { margin: 0; font-size: 18px; text-transform: uppercase; }
        .header h2 { margin: 4px 0 0; font-size: 14px; }
        table.meta { width: 100%; margin-bottom: 12px; }
        table.section { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
        table.section th, table.section td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        table.section th { background: #f2f2f2; }
        table.section td.num, table.section th.num { text-align: right; }
        .balance { max-width: 480px; margin-left: auto; }
        .balance td { padding: 4px 0; font-weight: bold; }
        .signatures { margin-top: 50px; display: table; width: 100%; }
        .signatures div { display: table-cell; width: 50%; text-align: center; }
        .signatures .line { border-top: 1px solid #1a1a1a; margin: 0 30px; padding-top: 4px; font-size: 11px; }
        .footer { margin-top: 30px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Borno State Geographic Information Service</h1>
        <h2>Bank Reconciliation Statement</h2>
    </div>

    <table class="meta">
        <tr>
            <td><strong>Account:</strong> {{ $reconciliation->account->account_name }}</td>
            <td><strong>Bank:</strong> {{ $reconciliation->account->bank_name }}</td>
            <td><strong>Account Number:</strong> {{ $reconciliation->account->account_number }}</td>
        </tr>
        <tr>
            <td><strong>Period:</strong> {{ $reconciliation->bankStatement->statement_from->format('d M Y') }} — {{ $reconciliation->bankStatement->statement_to->format('d M Y') }}</td>
            <td><strong>Status:</strong> {{ strtoupper($reconciliation->status) }}</td>
            <td><strong>Date:</strong> {{ $reconciliation->reconciliation_date->format('d M Y') }}</td>
        </tr>
    </table>

    <table class="section">
        <thead>
            <tr><th>Type</th><th>Source</th><th>Notes</th><th class="num">Amount</th></tr>
        </thead>
        <tbody>
            @foreach($reconciliation->items as $item)
                <tr>
                    <td>{{ ucfirst(str_replace('_', ' ', $item->item_type)) }}</td>
                    <td>
                        @if($item->cashbookEntry)
                            Cashbook: {{ $item->cashbookEntry->reference }}
                        @elseif($item->bankStatementLine)
                            Bank: {{ $item->bankStatementLine->reference ?? $item->bankStatementLine->description }}
                        @else
                            —
                        @endif
                    </td>
                    <td>{{ $item->notes }}</td>
                    <td class="num">{{ number_format((float) $item->amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="balance">
        <tr><td>Cashbook Balance</td><td class="num">₦{{ number_format((float) $reconciliation->cashbook_balance, 2) }}</td></tr>
        <tr><td>Bank Statement Balance</td><td class="num">₦{{ number_format((float) $reconciliation->bank_statement_balance, 2) }}</td></tr>
        <tr><td>Adjusted Cashbook Balance</td><td class="num">₦{{ number_format((float) $reconciliation->adjusted_cashbook_balance, 2) }}</td></tr>
        <tr><td>Adjusted Bank Balance</td><td class="num">₦{{ number_format((float) $reconciliation->adjusted_bank_balance, 2) }}</td></tr>
        <tr><td>Difference</td><td class="num">₦{{ number_format((float) $reconciliation->difference, 2) }}</td></tr>
    </table>

    <div class="signatures">
        <div><div class="line">Prepared By<br>{{ $reconciliation->preparer?->name ?? '—' }}</div></div>
        <div><div class="line">Approved By<br>{{ $reconciliation->approver?->name ?? '—' }}</div></div>
    </div>

    <div class="footer">Generated by the BOGIS Finance Management System on {{ now()->format('d M Y H:i') }}.</div>
</body>
</html>
